<?php

########################################################################
# Extension Manager/Repository config file for ext: "jobsearch"
#
# Auto generated by Extbase Kickstarter 2010-09-04
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Job Database',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Sebastian Michaelsen',
	'author_email' => 'sebastian.gebhard@googlemail.com',
	'author_company' => '',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'locator' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>